

all: qs_serial qs_pthread qs_peer 

qs_serial: qs_serial.c
	gcc -O3 -o ../build/qs_serial qs_serial.c

qs_pthread: qs_pthread.c
	gcc -O3 -o ../build/qs_pthread qs_pthread.c

qs_peer: qs_peer.c
	gcc -O3 -o ../build/qs_peer qs_peer.c