########################################################################
# Makefile for MPItutorial
#
########################################################################

CC         =  mpicc
CCFLAGS    =  -O3
LIBS       =  -lmpi

ass1:		main.c
	$(CC) $(CCFLAGS) -o mpifox main.c 

